[package]
name = "blinmaker"
version = "2.1.0"
authors = ["ilchub, drag0nhaze"]
edition = "2018"
license = "GNU GPLv3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
